export const thumbnailOptions = [
  {
    href: 'https://apexmarketstore.vercel.app/',
    title: 'ApexMarket',
    service: 'Full-Stack Digital Marketplace & Store',
    color: '#0ba360',
    gradient: 'linear-gradient(135deg, #0ba360 0%, #3cba92 100%)',
    tag: '🛒 Digital Commerce',
  },
  {
    href: 'https://auraagentai.vercel.app/',
    title: 'AURA OS',
    service: 'AI Agent Workspace & Productivity Engine',
    color: '#1e3c72',
    gradient: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)',
    tag: '🤖 AI Agent Workspace',
  },
  {
    href: 'https://indianagent.lovable.app/',
    title: 'IndianAgent',
    service: 'Intelligent Conversational & Research AI Agent',
    color: '#ea580c',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)',
    tag: '🇮🇳 Conversational AI',
  },
  {
    href: 'https://privateschat.lovable.app/',
    title: 'Private Chat',
    service: 'Encrypted & Minimal Real-Time Messaging',
    color: '#0f766e',
    gradient: 'linear-gradient(135deg, #0f766e 0%, #14b8a6 100%)',
    tag: '🔒 Private Messaging',
  },
  {
    href: 'https://khushal-jangid.github.io/toolbox-suite/',
    title: 'ToolBox Suite',
    service: '40+ Developer, Image & PDF Utilities',
    color: '#f857a6',
    gradient: 'linear-gradient(135deg, #f857a6 0%, #ff5858 100%)',
    tag: '🧰 40+ Online Utilities',
  },
  {
    href: 'https://khushal-jangid.github.io/pulse-remote-pc/#',
    title: 'PulseRemote PC',
    service: 'Wi-Fi Smartphone-to-PC Controller',
    color: '#654ea3',
    gradient: 'linear-gradient(135deg, #654ea3 0%, #eaafc8 100%)',
    tag: '📱 Wi-Fi Remote Control',
  },
  {
    href: 'https://folio-notes-tasks.surge.sh/download.html',
    title: 'Folio Notes',
    service: 'Paper-Feel Notes, Daily Tasks & Habits',
    color: '#ff9966',
    gradient: 'linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)',
    tag: '📝 Productivity Workspace',
  },
  {
    href: 'https://khushal-jangid.github.io/spydy-electron/',
    title: 'Spydy Reminder',
    service: 'Spider-Man Style Desktop Overlay App',
    color: '#e52d27',
    gradient: 'linear-gradient(135deg, #e52d27 0%, #b31217 100%)',
    tag: '🕷️ Desktop App',
  },
  {
    href: 'https://apex-studio-dev.surge.sh/index.html#',
    title: 'Apex Studio',
    service: 'Creative Web Development & Digital Lab',
    color: '#4f46e5',
    gradient: 'linear-gradient(135deg, #4f46e5 0%, #06b6d4 100%)',
    tag: '🎨 Creative Web Studio',
  },
  {
    href: 'https://khushal-jangid.github.io/khushal-webpage/filmhub/',
    title: 'FilmHub',
    service: '93 Verified Movie, OTT & Anime Platforms',
    color: '#dc2626',
    gradient: 'linear-gradient(135deg, #dc2626 0%, #f97316 100%)',
    tag: '🎬 Streaming Directory',
  },
];
