export const thumbnailOptions = [
  {
    href: 'https://github.com/khushal-jangid/ai-agent-app',
    title: 'AURA OS',
    service: 'AI Agent Workspace & React Vite',
    color: '#1e3c72',
    gradient: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)',
    tag: '🤖 AI Agent Workspace',
  },
  {
    href: 'https://github.com/khushal-jangid/digital-marketplace',
    title: 'ApexMarket',
    service: 'Full-Stack Digital Marketplace',
    color: '#0ba360',
    gradient: 'linear-gradient(135deg, #0ba360 0%, #3cba92 100%)',
    tag: '🛒 Digital Commerce',
  },
  {
    href: 'https://github.com/khushal-jangid/toolbox-suite',
    title: 'ToolBox Suite',
    service: '40+ Developer & PDF Utilities',
    color: '#f857a6',
    gradient: 'linear-gradient(135deg, #f857a6 0%, #ff5858 100%)',
    tag: '🧰 40+ Online Utilities',
  },
  {
    href: 'https://github.com/khushal-jangid/pulse-remote-pc',
    title: 'PulseRemote PC',
    service: 'Wi-Fi Smartphone-to-PC Controller',
    color: '#654ea3',
    gradient: 'linear-gradient(135deg, #654ea3 0%, #eaafc8 100%)',
    tag: '📱 Wi-Fi Remote Control',
  },
  {
    href: 'https://github.com/khushal-jangid/folio-notes-tasks',
    title: 'Folio Notes',
    service: 'Paper Notes & Daily Tasks Web App',
    color: '#ff9966',
    gradient: 'linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)',
    tag: '📝 Productivity Workspace',
  },
  {
    href: 'https://github.com/khushal-jangid/spydy-electron',
    title: 'Spydy Reminder',
    service: 'Spider-Man Desktop Overlay App',
    color: '#e52d27',
    gradient: 'linear-gradient(135deg, #e52d27 0%, #b31217 100%)',
    tag: '🕷️ Desktop App',
  },
];
